
-- @CREATE-PRODUCT
CREATE TABLE IF NOT EXISTS Product (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(256) NOT NULL,
	Price DECIMAL(10, 2) NOT NULL
);

-- @CREATE-ALIAS
CREATE TABLE IF NOT EXISTS ProductAlias (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Alias VARCHAR(256) NOT NULL,
	ProductID INTEGER NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

-- @CREATE-CATEGORY
CREATE TABLE IF NOT EXISTS Category (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR(256) NOT NULL
);

-- @CREATE-CATEGORY-PRODUCT
CREATE TABLE IF NOT EXISTS Category_Product (
	ProductID INTEGER NOT NULL,
	ProductCategoryID INTEGER NOT NULL,
	PRIMARY KEY (ProductID, ProductCategoryID),
	FOREIGN KEY (ProductID) REFERENCES Product(ID),
	FOREIGN KEY (ProductCategoryID) REFERENCES Category(ID)
);

-- @CREATE-SALE
CREATE TABLE IF NOT EXISTS Sale(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ProductID INTEGER NOT NULL,
	Quantity INT NOT NULL,
	Price INT NOT NULL,

	FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

-- @CREATE-TICKET
CREATE TABLE IF NOT EXISTS Ticket(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Date TIMESTAMP NOT NULL
);

-- @CREATE-TICKET-SALE
CREATE TABLE IF NOT EXISTS Ticket_Sale(
	TicketID INTEGER NOT NULL,
	SaleID INTEGER NOT NULL,
	FOREIGN KEY (TicketID) REFERENCES Ticket(ID),
	FOREIGN KEY (SaleID) REFERENCES Sale(ID)
);


-- @DROP-ALL-TABLES
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS ProductAlias;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Category_Product;
DROP TABLE IF EXISTS Sale;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Ticket_Sale;
