-- @LIST-PRODUCTS
SELECT * FROM Product;

-- @LIST-PRODUCTS-WHERE-PRICE-IS
SELECT * FROM Product WHERE Price == ?;

-- @LIST-ALIASES
SELECT * FROM Alias;

-- @LIST-CATEGORIES
SELECT * FROM Category;

-- @LIST-CATEGORIES
SELECT * FROM Category_Product;

-- @LIST-CATEGORIES
SELECT * FROM Sale;

-- @LIST-CATEGORIES
SELECT * FROM Ticket;

-- @LIST-CATEGORIES
SELECT * FROM Ticket_Sale;
